#ifndef WIYATA_OPEN_KATTIS_REVERSED_BINARY_NUMBERS_H
#define WIYATA_OPEN_KATTIS_REVERSED_BINARY_NUMBERS_H

int reversed_binary_numbers(int n);

#endif /* WIYATA_OPEN_KATTIS_REVERSED_BINARY_NUMBERS_H */
