#ifndef WIYATA_LEETCODE_BEST_TIME_TO_BUY_AND_SELL_STOCK
#define WIYATA_LEETCODE_BEST_TIME_TO_BUY_AND_SELL_STOCK

int maxProfit(int* prices, int pricesSize);

#endif /* WIYATA_LEETCODE_BEST_TIME_TO_BUY_AND_SELL_STOCK */
