name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Build and test
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build
          options: --verbose
          meson-version: 0.63.2
